### ISSUE TITLE
Some card IDs off by one

### ISSUE THREAD

**Issue by GenericMadScientist** [duke1102/fmscrambler#2]
The card IDs for the second material and fusion result are off by one. For example, with seed #171236062 the first fusion in the log is
=> Hitotsu-me Giant (3) + Man Eater (157) = Wicked Dragon with the Ersatz Head (297)
but Man Eater's ID is 158 and Wicked's ID is 298.

**Comment by GenericMadScientist** [comment]
Oh, it seems there's a bit more to this. To make sure I downloaded the most recent version of this hosted on github, then randomised with seed 0 and both options unticked. The first fusion in the log is
=> Hitotsu-me Giant (3) + Spirit of the Mountain (524) = Morphing Jar (590).
If I open up the WA_MRG.MRG with the mod tool, then I see that in fact that fusion should be
=> Mystical Elf (2) + Spirit of the Mountain (525) = Morphing Jar (591).

**Comment by duke1102** [comment]
Alright, I already think what's going wrong here and will release a fix soon.
