### ISSUE TITLE
Card drop randomizer crashes the program

### ISSUE THREAD

**Issue by Midnaait** [duke1102/fmscrambler#25]
Title is self explanatory, when you only check that option and click randomize, it closes the program.
Used the SLUS option because .cue also didn't work for me (crashes too)
The only combination that works for this option is Card Drop + Random fusions + random duelist deck. Thanks for reading if you're there!

**Comment by duke1102** [comment]
Hey @Midnaait!
Thanks for reporting the issue. It's rather strange. 
You did use the SLUS_014.11 (YGO! FM NTSC-U) version, right? Other versions are (currently) not supported.

Could you go ahead and create a checksum of your YGO! FM .BIN/.CUE files, so I can compare those with the image I use? 
You can use this tool: [HashMyFiles](http://www.nirsoft.net/utils/hashmyfiles-x64.zip) [(Alternative 32bit)](http://www.nirsoft.net/utils/hashmyfiles.zip)
Just run it and click under the top menu _"File" -> "Add Files"_ and add the .BIN of your YGO! FM image. It will then automatically calculate the checksum of the files. 
Right-click the entries and _"Copy SHA1"_ and then post it here.

As of right now I must admit there isn't really a functionality that generates error/debug logs on exceptions and crashes, I might spend the coming weekend to implement such feature.

This is the SHA1 of my game image:   
`Yu-Gi-Oh! Forbidden Memories (USA).bin	        d5785a41900a10968d4a28a390666c4b9879b796`

**Comment by Midnaait** [comment]
Yeah, I'm currently using that version, NTSC-U. the SHA1 I got from that is `d5785a41900a10968d4a28a390666c4b9879b796`

**Comment by Midnaait** [comment]
Fixed after 0.1.9 release 👀
