### ISSUE TITLE
Program crashes if the seed field is blank upon randomisation

### ISSUE THREAD

**Issue by GenericMadScientist** [duke1102/fmscrambler#5]
Similarly, leading 0s in the seed field also cause a crash upon randomisation.

**Comment by GenericMadScientist** [comment]
I can also crash it by putting text in said field. I'm unable to type it in directly, but I can paste in what I want it seems. Although it still gets truncated to nine characters.

**Comment by duke1102** [comment]
Okay, for leading 0s there is no check in yet to prevent those. The way Seeds work is by giving it a 32 bit Integer value.

With the textfield validation I have to do some more research, right now it uses a simple regular expression to check if the input is a number whenever you type something in. I also set the max limit of characters to 9.
